### ISSUE TITLE
Custom MOTD?

### ISSUE THREAD

**Issue by CobaltGit** [spezifanta/hldm-docker#3]
I'm trying to set a custom MOTD for the server by exec'ing an interactive shell in the container and then doing
```
$ cd valve
$ cat << EOF > motd.txt
> blah blah blah
> EOF
$ ^D
```
After exiting the shell I restart the container and join the server to see that the MOTD has been reverted back to the default. Is there anything I'd be able to do?

I've tried mounting the valve directory as a volume but everything disappears after I restart the container except for the config directory

Complete Docker noob here wondering what to do :D

**Comment by CobaltGit** [comment]
Quick update:

I just tried mounting the valve directory as a volume and the server refused to start citing missing files (all that's there on both sides (host and container) is the config directory.)

**Comment by CobaltGit** [comment]
Oh and here's the compose file minus the valve data dir:

```yaml
version: "2"

services: 
  hldm:
    image: spezifanta/hldm
    tty: true
    stdin_open: true
    cpus: "2"
    mem_limit: "2500m"
    ports:
      - '27015:27015'
      - '27015:27015/udp'
      - '26900:26900/udp'
    volumes:
      - './config:/opt/steam/hldm/valve/config'
    container_name: hldm
```
